//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCollection
    {
        public int Collection_ID { get; set; }
        public Nullable<int> Detail_ID { get; set; }
        public string Collection_Name { get; set; }
        public string Collection_Type { get; set; }
        public string Collection_Start_Date__Planned_ { get; set; }
        public string Collection_Start_Date__Actual_ { get; set; }
        public string Collection_End_Date__Planned_ { get; set; }
        public string Collection_End_Date__Actual_ { get; set; }
    }
}
