//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetail
    {
        public int Detail_ID { get; set; }
        public Nullable<int> Follow_Up_ID { get; set; }
        public string Keywords { get; set; }
        public string Steward { get; set; }
        public Nullable<bool> Universe_Survey { get; set; }
        public Nullable<bool> Sample_Survey { get; set; }
        public Nullable<bool> Cross_Sectional { get; set; }
        public Nullable<bool> Longitudinal { get; set; }
        public Nullable<bool> Voluntary { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<bool> Required_for_Benefits { get; set; }
        public string Requirement_Reason { get; set; }
        public Nullable<bool> Program_Monitoring { get; set; }
        public Nullable<bool> Grantee_Reports { get; set; }
        public string Authorizing_Law { get; set; }
        public string SORN { get; set; }
        public Nullable<bool> Could_Be_Public { get; set; }
        public string Publication_Date__Stats_ { get; set; }
        public string Publication_Type__Stats_ { get; set; }
        public string Publication_URL__Stats_ { get; set; }
        public string Publication_Date__Data_ { get; set; }
        public string Publication_URL__Data_ { get; set; }
        public string Restricted_Use_Date { get; set; }
        public Nullable<bool> Planned_Restricted_Data { get; set; }
        public Nullable<int> Students { get; set; }
        public Nullable<int> Staff { get; set; }
        public Nullable<int> Institutions { get; set; }
        public Nullable<int> Programs { get; set; }
        public string Other_Subject { get; set; }
        public Nullable<int> Age_0_2 { get; set; }
        public Nullable<int> Age_3_5 { get; set; }
        public Nullable<int> Age_6_21 { get; set; }
        public Nullable<int> Age_Older_Than_21 { get; set; }
        public Nullable<int> Age_NA { get; set; }
        public Nullable<int> Pre_K { get; set; }
        public Nullable<int> Elementary { get; set; }
        public Nullable<int> Middle { get; set; }
        public Nullable<int> High_School { get; set; }
        public Nullable<int> Postsecondary { get; set; }
        public Nullable<int> Graduate { get; set; }
        public Nullable<int> Continued_Technical_Ed { get; set; }
        public Nullable<int> Adult_Education { get; set; }
        public Nullable<int> General_Adult { get; set; }
        public Nullable<int> Education_Level_NA { get; set; }
        public string Other_Population { get; set; }
        public string Subject_Population_Detail { get; set; }
        public Nullable<bool> School_Institution_Data { get; set; }
        public Nullable<bool> LEA_Data { get; set; }
        public Nullable<bool> State_Data { get; set; }
        public Nullable<bool> Region_Data { get; set; }
        public Nullable<bool> National_Data { get; set; }
        public string Other_Data_Level { get; set; }
        public string Bureau_Code { get; set; }
        public string Program_Code { get; set; }
        public string JSON_Unique_Identifier { get; set; }
        public string SORN_URL { get; set; }
        public string Public_Access_Level { get; set; }
        public string Confidentiality_Restrictions { get; set; }
    }
}
