//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDataset_
    {
        public System.Guid Dataset_ID { get; set; }
        public string Dataset_Title { get; set; }
        public string Dataset_Location { get; set; }
        public string Dataset_Location_Detail { get; set; }
        public Nullable<int> Dataset_Restriction { get; set; }
    }
}
