//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElement_
    {
        public System.Guid Element_ID { get; set; }
        public string Element_Name { get; set; }
        public string Element_Label { get; set; }
        public string Element_Extended_Definition { get; set; }
        public string Element_Question { get; set; }
        public string Element_Type { get; set; }
        public Nullable<int> Vector { get; set; }
        public Nullable<int> EDFacts { get; set; }
        public Nullable<int> IDEA { get; set; }
    }
}
