//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFollow_Up
    {
        public int Follow_Up_ID { get; set; }
        public string Follow_Up_Name { get; set; }
        public string Follow_Up_Abbreviation { get; set; }
        public string Follow_up_Abstract { get; set; }
        public Nullable<int> Longitudinal_Follow_Up { get; set; }
        public Nullable<int> Preceding_Follow_Up_ID { get; set; }
        public Nullable<int> Study_ID { get; set; }
        public string Subject_Terms_List { get; set; }
        public string Collection_Date_List { get; set; }
    }
}
