//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProgram
    {
        public int Program_ID { get; set; }
        public Nullable<int> Division_ID { get; set; }
        public string Program_Name { get; set; }
        public string Program_Old_Name_1 { get; set; }
        public string Program_Old_Name_2 { get; set; }
        public string Program_Old_Name_1_Duration { get; set; }
        public string Program_Old_Name_2_Duration { get; set; }
        public string Program_Abbreviation { get; set; }
        public string Program_Old_Name_1_Abbr { get; set; }
        public string Program_Old_Name_2_Abbr { get; set; }
        public string Program_Description { get; set; }
        public Nullable<int> Primary_Contact_ID { get; set; }
        public Nullable<int> C2nd_Contact_ID { get; set; }
        public Nullable<int> C3rd_Contact_ID { get; set; }
        public Nullable<int> Supervisor_ID { get; set; }
        public string Study_List { get; set; }
        public string Steward_List { get; set; }
        public Nullable<bool> Search_Variables { get; set; }
        public Nullable<int> Study_Count { get; set; }
    }
}
