//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudy
    {
        public int Study_ID { get; set; }
        public Nullable<int> Program_ID { get; set; }
        public string Study_Name { get; set; }
        public string Study_Old_Name_1 { get; set; }
        public string Study_Old_Name_2 { get; set; }
        public string Study_Old_Name_1_Duration { get; set; }
        public string Study_Old_Name_2_Duration { get; set; }
        public string Study_Abbreviation { get; set; }
        public string Study_Old_Name_1_Abbr { get; set; }
        public string Study_Old_Name_2_Abbr { get; set; }
        public string Study_Website { get; set; }
        public string Study_Abstract { get; set; }
        public string Frequency { get; set; }
        public string Most_Recent_Year { get; set; }
        public Nullable<bool> Releasable { get; set; }
        public string Steward_List { get; set; }
        public string Geographic_Coverage_List { get; set; }
        public string Observation_Unit_List { get; set; }
        public string Population_List { get; set; }
        public string Data_Types_List { get; set; }
        public string Data_Collection_Purpose_List { get; set; }
        public string Authorizing_Law_List { get; set; }
        public string SORN_List { get; set; }
        public string Target_Population_Age_Range_List { get; set; }
        public string Target_Population_Education_Level_List { get; set; }
        public string Subject_Terms_List { get; set; }
        public string Initial_Report_List { get; set; }
        public string Data_Availability_List { get; set; }
        public string Restricted_Use_Date_List { get; set; }
        public string Could_Be_Public_List { get; set; }
        public string Collection_Date_List { get; set; }
        public Nullable<bool> Search_Variables { get; set; }
        public string Bureau_Code_List { get; set; }
        public string Program_Code_List { get; set; }
        public string JSON_Unique_Identifier_List { get; set; }
        public string SORN_URL_List { get; set; }
        public string Public_Access_Level_List { get; set; }
        public string Confidentiality_Restrictions_List { get; set; }
    }
}
