//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSDLink_
    {
        public System.Guid SD_Link_ID { get; set; }
        public Nullable<int> Study_ID { get; set; }
        public Nullable<System.Guid> Dataset_ID { get; set; }
    }
}
